### ISSUE TITLE
throughputs: simplification

### ISSUE THREAD

**Issue by niXman** [Vuniverse0/mingwInstaller#2]
1) https://github.com/Vuniverse0/mingwInstaller/blob/main/src/icon.cpp#L2168

why not just use `sizeof(icon)` ?

2) https://github.com/Vuniverse0/mingwInstaller/blob/main/src/icon.hpp#L4

this is very strange decision...
why not return a `std::pair` from a function?
smth like this:
```cpp
std::pair<const std::uint8_t *, std::size_t>
getIcon();
```

3) https://github.com/Vuniverse0/mingwInstaller/blob/main/src/link.cpp#L42

why that function returns `double`?
why not just use [SHFileOperationA](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shfileoperationa) ?

4) logo.cpp/hpp, the same questions as for 1 and 2.

best!

**Comment by Vuniverse0** [comment]
1. Yes
2. Used self made struct. This way I was not include <utility> header.
3. I will try make it. Added as TODO.
4. Yes
    Thanks.

**Comment by Vuniverse0** [comment]
Done.
    Thanks.
