### ISSUE TITLE
to compress executable

### ISSUE THREAD

**Issue by niXman** [Vuniverse0/mingwInstaller#3]
hi,

could you please try to compress executable using UPX?
now the installer executable has ~7 MB and I think it could be less...

best!

**Comment by Vuniverse0** [comment]
Compression by UPX decrease file size by ~40% but make binary was unsafe.  
https://www.virustotal.com/gui/file/a875638764e8aa1a45d90782f7e14409bdf1ebac9160812c6a1923e04a31d306?nocache=1
![image](https://user-images.githubusercontent.com/40805159/192213232-3cc1b81b-e949-4957-9bf5-791045d1e5b8.png)
    Thanks.
